# Generated by Django 2.0.4 on 2018-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_number', models.IntegerField(default=0, verbose_name='图片序号')),
                ('picture_word', models.TextField(blank=True, null=True, verbose_name='图片字幕')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='', max_length=100, verbose_name='节目名称')),
                ('similar_bench', models.IntegerField(default=50, verbose_name='相似度门限')),
                ('process_date', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('fps_interval', models.IntegerField(default=2, verbose_name='每秒抽取帧数')),
                ('picture_names', models.TextField(blank=True, null=True, verbose_name='图片文件名')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(max_length=100)),
                ('scene_keywords', models.CharField(max_length=1000, verbose_name='关键词')),
                ('scene_descript', models.TextField(blank=True, null=True, verbose_name='场景')),
                ('similar_bench', models.IntegerField(default=50, verbose_name='相似度门限')),
                ('first_frame', models.TextField(blank=True, null=True, verbose_name='场景第一帧')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=100)),
                ('segmengt_keywords', models.CharField(max_length=1000)),
                ('segment_descript', models.TextField(blank=True, null=True, verbose_name='片段')),
                ('segment_start_time', models.DateTimeField(auto_now=True, verbose_name='create time')),
            ],
        ),
    ]
