# Generated by Django 2.0.4 on 2018-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180412_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(default='', max_length=100, verbose_name='系列名称')),
                ('surface_image', models.CharField(default='', max_length=1024, verbose_name='封面图片')),
                ('series_type', models.CharField(default='', max_length=32, verbose_name='系列类型')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
        migrations.AddField(
            model_name='program',
            name='series_name',
            field=models.CharField(default='', max_length=100, verbose_name='系列名称'),
        ),
    ]
