# Generated by Django 2.0.4 on 2018-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180425_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='series_name',
            field=models.CharField(default='', max_length=100, verbose_name='系列名称'),
        ),
    ]
