# Generated by Django 2.0.4 on 2018-04-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20180426_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_bench', models.IntegerField(default=50, verbose_name='相似度门限')),
                ('file_check_interval', models.IntegerField(default=10, verbose_name='新文件检测间隔')),
                ('frame_per_second', models.IntegerField(default=2, verbose_name='抽帧频率（每秒抽多少帧）')),
            ],
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='picture_names',
            new_name='frame_names',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='segment_name',
            new_name='program_name',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='segment_start_time',
        ),
        migrations.AddField(
            model_name='program',
            name='face_num',
            field=models.TextField(blank=True, null=True, verbose_name='人脸图片'),
        ),
        migrations.AddField(
            model_name='program',
            name='frame_text',
            field=models.TextField(blank=True, null=True, verbose_name='图片字幕'),
        ),
        migrations.AddField(
            model_name='program',
            name='segment_num',
            field=models.TextField(blank=True, null=True, verbose_name='场景第一帧'),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_end_num',
            field=models.IntegerField(default=0, verbose_name='当前段结束帧'),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_start_num',
            field=models.IntegerField(default=0, verbose_name='当前段结束帧'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fps_interval',
            field=models.IntegerField(default=0, verbose_name='每秒抽取帧数'),
        ),
    ]
