# Generated by Django 2.0.4 on 2018-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20180428_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='audience',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='award',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='content_descript',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='copy_right',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='episodes_num',
            field=models.IntegerField(default=1, max_length=100, verbose_name='集数'),
        ),
        migrations.AddField(
            model_name='series',
            name='key_person',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='nake_name',
            field=models.CharField(default='', max_length=100, verbose_name='别名'),
        ),
        migrations.AddField(
            model_name='series',
            name='productor',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='publisher',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='right_area',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='right_others',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='series_keywords',
            field=models.CharField(default='', max_length=500, verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='series',
            name='source_privider',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='source_type',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='start_time',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='taken_date',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='taken_place',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='use_times',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='series',
            name='version',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
    ]
